language: python
python:
- '3.5'
addons:
  postgresql: '9.4'
install:
- pip install -r requirements.txt
- pip install -r requirements/development.txt
- pip install coveralls
- npm install
- npm install -g grunt-cli bower
before_script:
- psql -c 'CREATE DATABASE superpunch;' -U postgres
script:
- make migrate
- make test
- make collectstatic
after_success:
- coveralls
