# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multisites.utils.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.Site')),
                ('default_meta_title', models.CharField(blank=True, max_length=128, null=True)),
                ('default_meta_description', models.CharField(blank=True, max_length=128, null=True)),
                ('default_meta_keywords', models.CharField(blank=True, max_length=128, null=True)),
                ('default_meta_image', models.ImageField(blank=True, help_text='image/png, 1200px * 630px Recommended.', null=True, upload_to=multisites.utils.image.default_meta_image_upload_to)),
                ('facebook_app_id', models.CharField(blank=True, help_text='<a href="https://developers.facebook.com/" target="_blank">Facebook Developers</a>', max_length=32, null=True)),
                ('facebook_page_id', models.CharField(blank=True, max_length=32, null=True)),
                ('facebook_page_slug', models.CharField(blank=True, max_length=32, null=True)),
                ('google_analytics_tracking_id', models.CharField(blank=True, help_text='<a href="http://www.google.com/analytics/" target="_blank">Google Analytics</a>', max_length=32, null=True)),
                ('naver_site_verification', models.CharField(blank=True, help_text='<a href="http://webmastertool.naver.com/" target="_blank">네이버 웹마스터도구</a>', max_length=128, null=True)),
                ('naver_analytics_tracking_id', models.CharField(blank=True, help_text='<a href="http://analytics.naver.com/" target="_blank">네이버 애널리틱스</a>', max_length=32, null=True)),
                ('ascii_art', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'multisites_site_profile',
                'default_related_name': 'site_profile',
            },
        ),
    ]
