# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tidbits.utils.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('feed_url', models.URLField(blank=True, null=True, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tidbit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('original_url', models.URLField(blank=True, null=True, unique=True, verbose_name='원문 주소')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문')),
                ('author', models.CharField(blank=True, max_length=64, null=True, verbose_name='작성자')),
                ('original_html', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=128, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=256, null=True)),
                ('meta_image_url', models.URLField(blank=True, null=True)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to=tidbits.utils.image.meta_image_upload_to)),
                ('is_meta_crawled', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tidbits.Provider')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'get_latest_by': 'created_at',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tidbit',
            unique_together=set([('provider', 'original_url')]),
        ),
    ]
